// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjgcteapggmoiaudmslb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqZ2N0ZWFwZ2dtb2lhdWRtc2xiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNDUyNzgsImV4cCI6MjA1NTYyMTI3OH0.ptHyA7I0Ms1dOa0ubwH93_h6LNjT42sa8hAjPkxWpBk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);